config/routes.rb
Rails.application.routes.draw do
  match '/tags/search', {:via => :get, :to => 'tags#search'}
  resources :tags

  match '/', :via => [:get], :to => redirect('/home.html')
  match('/recipes/:id/add_tag', {:via => :post, :to => 'recipes#add_tag'})
  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :title, :presence => true
  validates :ingredients, :presence => true
  validates :instructions, :presence => true

  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @tags = Tag.all
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_tag
    @recipe = Recipe.find(params[:id])
    newTag = Tag.new(params[:tag])
    if newTag.valid?
      newTag.save
      @recipe.tags << newTag
      @recipe.save
    render 'show.html.erb'
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :author, :ingredients, :instructions)
    end
  end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  #search
  def search
    if !params[:search_string].nil?
    search_string = params[:search_string].strip
    @tags = Tag.where(:name => search_string)
  end
end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_header.html.erb
<head>
  <link href="../../assets/stylesheets/bootstrap.css" rel="stylesheet" type="text/css">
  <link href="../../assets/stylesheets/recipes-styles.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <title>Share Recipes</title>
</head>
<body>
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-3">
      <h1><span class="logo">
        ShareRecipes!
      </span>
      </h1>
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-6">
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand select" href="http://localhost:3000/home.html"><span class="logo">SR!<span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="select"><a href="http://localhost:3000/recipes/new">Add a Recipe <span class="sr-only">(current)</span></a></li>
        <li class="select"><a href="http://localhost:3000/recipes">See All Recipes</a></li>
        <li class="select"><a href="http://localhost:3000/tags/search">Search Recipes by Tag</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    </div>
  </div>
  <div class="row spacer">
  </div>

app/views/recipes/edit.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
    <h1>Editing Recipe</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @recipe %> |
    <%= link_to 'Back', recipes_path %>
  </div>
  <div class="col-md-2">
  </div>

</div>

app/views/recipes/index.html.erb
<%= render('header') %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
    <h1>Listing Recipes</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Ingredients</th>
          <th>Instructions</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @recipes.each do |recipe| %>
          <tr>
            <td><%= recipe.title %></td>
            <td><%= recipe.author %></td>
            <!-- <td><%= recipe.ingredients %></td>
            <td><%= recipe.instructions %></td> -->
            <td><%= link_to 'Show', recipe %></td>
            <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
            <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Recipe', new_recipe_path %>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/recipes/new.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
    <h1>New Recipe</h1>

    <%= render 'form' %>

    <%= link_to 'Back', recipes_path %>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/recipes/show.html.erb
<%= render('header') %>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Title:</strong>
        <%= @recipe.title %>
      </p>

      <p>
        <strong>Author:</strong>
        <%= @recipe.author %>
      </p>

      <p>
        <strong>Ingredients:</strong>
        <%= @recipe.ingredients %>
      </p>

      <p>
        <strong>Instructions:</strong>
        <%= @recipe.instructions %>
      </p>

      <p>
        <strong>Tags:</strong>
        <% @recipe.tags.each do |tag| %>
        <%= tag.name %>,
        <% end %>
      </p>

      <form action="/recipes/<%=@recipe.id%>/add_tag" method="post">
        <div class="field">
          <label for="tag_name">Tag Name</label><br>
          <input type="text" name="tag[name]" id="tag_name" />
        </div>
        <div class="actions">
          <input type="submit" name="commit" value="Add Tag" />
        </div>
      </form>


      <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
      <%= link_to 'Back', recipes_path %>
    <div class="col-md-2">
    </div>
  </div>
</div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_header.html.erb
<head>
  <link href="../../assets/stylesheets/bootstrap.css" rel="stylesheet" type="text/css">
  <link href="../../assets/stylesheets/recipes-styles.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <title>Share Recipes</title>
</head>
<body>
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-3">
      <h1><span class="logo">
        ShareRecipes!
      </span>
      </h1>
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-6">
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://localhost:3000/home.html"><span class="logo">SR!<span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="select"><a href="http://localhost:3000/recipes/new">Add a Recipe <span class="sr-only">(current)</span></a></li>
        <li class="select"><a href="http://localhost:3000/recipes">See All Recipes</a></li>
        <li class="select"><a href="http://localhost:3000/tags/search">Search Recipes by Tag</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    </div>
  </div>
  <div class="row spacer">
  </div>

app/views/tags/edit.html.erb
<%= render('header') %>
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<%= render('header') %>
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<%= render('header') %>
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/search.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>

  <div class="col-md-8 main">


    <h2>Search for Recipes by Tag</h2>

    <form action="/tags/search" method="get">
      <label for="search_by_tag">Tag Name:</label>
      <input id="search_by_tag" type="text" name="search_string"/>
      <input type="submit" value="Search"/>
    <form>

    <% if !@tags.nil? %>
      <% if !@tags.empty? %>
        <h3>Recipes Found</h3>
          <% @tags.each do |tag| %>
            <%= tag.recipe.title %><br>
          <% end %>
          <% else %>
        <h3>No Recipes Found :(</h3>
      <% end %>
    <% end %>

  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/tags/show.html.erb
<%= render('header') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>